// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5H-ur0-nOfNJpZMQoOf9nalk4nHat4iE',
    appId: '1:845555185745:web:d4115b20fb1a5decee2070',
    messagingSenderId: '845555185745',
    projectId: 'edtech-97c01',
    authDomain: 'edtech-97c01.firebaseapp.com',
    storageBucket: 'edtech-97c01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoeMnR7RL_cFVK737EvriT4LrtDqYVrE4',
    appId: '1:845555185745:android:690eb6cf27d0814fee2070',
    messagingSenderId: '845555185745',
    projectId: 'edtech-97c01',
    storageBucket: 'edtech-97c01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2H9ATyv4466hMpDcXF7rQ3BBvKOe4anY',
    appId: '1:845555185745:ios:809510d821977bcfee2070',
    messagingSenderId: '845555185745',
    projectId: 'edtech-97c01',
    storageBucket: 'edtech-97c01.appspot.com',
    iosBundleId: 'com.example.edtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2H9ATyv4466hMpDcXF7rQ3BBvKOe4anY',
    appId: '1:845555185745:ios:2b2c6bcec313cd1bee2070',
    messagingSenderId: '845555185745',
    projectId: 'edtech-97c01',
    storageBucket: 'edtech-97c01.appspot.com',
    iosBundleId: 'com.example.edtech.RunnerTests',
  );
}
